### PR TITLE
Remove trailing whitespace from *.cpp and *.h

### PR DESCRIPTION
**Pull request by atlimit8**
Minor tidying mostly because my preferred editors won't listen when I tell them to not remove trailing whitespace.

### CODE REVIEW

**Comment by MeridianOXC** [comment]
Thumbs down.
Unless this is enforced somehow, it will anyway be broken with the next commit.

**Comment by atlimit8** [comment]
Expanded scope (maybe too much?).
Solved the enforcement issue; Travis-CI will reject such commits.
Need to find Mac OS build issue.

**Comment by atlimit8** [comment]
I have reverted what should be more than enough to fix any build issue caused by this.
Is it possible that Traivis-CI Mac OS build is broken.
Mac tester may be required here.
```
[100%] Linking CXX executable ../openxcom.app/Contents/MacOS/openxcom
Error copying directory from "/usr/local/lib/libSDL_gfx.dylib" to "/Users/travis/build/SupSuper/OpenXcom/openxcom.app/Contents/Frameworks/libSDL_gfx.dylib".
make[2]: *** [openxcom.app/Contents/MacOS/openxcom] Error 1
make[2]: *** Deleting file `openxcom.app/Contents/MacOS/openxcom'
make[1]: *** [src/CMakeFiles/openxcom.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by atlimit8** [comment]
Travis-CI didn't like the two before script actions just on Mac OS.
I still need to clean this up now that I found the problem.

**Comment by atlimit8** [comment]
Probably way too late in this projects life, especially with the forks, to add this. Oh well.

**Pull request closed without merging**
