### PR TITLE
Simple custom recolors

### PR DESCRIPTION
**Pull request by Yankes**
Support for TFTD aquanauts recoloring.
One drawback it don't have default recoloring for all armors like current version.
Evey one who want use different colors for nationality in his sprite should add line like for `STR_NONE_UC`.

Additional I added option for aliens and civilians too. All code doing it is in last commit, can be skipped.
Only important change its do is move place where seed is loaded form save. This was done to preventing clobbering current seed by using `RNG` in `BattleUnit` constructor.

BTW for completion, do you want add option for recoloring corpses in battlescape and inventory?

### CODE REVIEW

**Comment by Warboy1982** [comment]
i'm pretty sure you can use calls to std::rand() with modulo max value+1 to randomize without skewing the seed, like i do in tile.cpp to randomize smoke/fire patterns on load.

**Comment by Yankes** [comment]
Right, I only do it because I wanted to stick to our RNG, do you want this reverted (and changed to std::rand()) or can it pass?

**Comment by Warboy1982** [comment]
yeah, best to stick to std::rand() for the battleunit constructor, as it gets called on game load anyway, so a save/load would skew it

**Comment by Yankes** [comment]
Ok I rewritten history, There is no RNG in commit anymore.

**Comment by Warboy1982** [comment]
cheers man!

**Comment by redv** [comment]
Why need recolor each frame? You can recolor one time during loading of resources or on demand. Then for each pair ```std::pair<Uint8, Uint8> face_color``` you will have ready to use surface. In fact this is a cache of surfaces. Such pairs is not so much as it seems.

**Comment by Yankes** [comment]
I don't think that coping every surface 8 times will be faster (you faster hit memory limits that cpu ones). My tests shows that you need lot of more operations per pixel to see any performance problems, another thing is Its a lot of easier to expand this with new options, I plan add recoloring for rank and 3 color for race (or random for aliens). But this will be probably for my extended version.

**Comment by redv** [comment]
Is it possible to do a dynamic recoloring? For example: if i want to change the ```face_color``` (race_color, rank_color) in a code, then whether will change looks of the sprite on the screen?

**Comment by Yankes** [comment]
This code don't allow that, its because result is cached before is redrawn on screen. This will cause delay of color change. But I once create more robust version that  allowed recoloring in real time, example:
https://www.youtube.com/watch?v=_G34PHMiBv0
One important part I needed to do was drop of unit sprite cache and draw directly to surface.
Only problem I have with that was I made it too robust, adding custom scripts for recoloring only was overkill. But still I didn't see any big performance drops when I did that. To made significant framerate drop I did 10 times more pixel recolors than was possible in normal OXC play.

**Pull request merged**
