### PR TITLE
Feature/travis

### PR DESCRIPTION
**Pull request by rcreasey**
Don't merge this until we talk on IRC.  I'll need @SupSuper to make a (free) travis account.

Here's an example of what this does: 
https://travis-ci.org/rcreasey/OpenXcom/jobs/76909855

Note, that this won't replace the nightly build system; this will only run CI on every commit made without actually producing builds for download.

### CODE REVIEW

**Comment by rcreasey** [comment]
I got travis to enable 'osx' builds for this as well.  I'm going try and get that working as well. 

It looks like @SupSuper got Travis setup:
https://travis-ci.org/SupSuper/OpenXcom

So, this pr is good to be accepted so long as the Travis CI service gets enabled on the main github repository.

**Comment by rcreasey** [comment]
Ok, I borrowed some of @JonnyH's travis magic and got cmake working cross platform:
https://travis-ci.org/rcreasey/OpenXcom/builds/77096192

Also, notice this pull request has the awesome 'All checks have passed'.

Here comes the README badge: [Build Status](https://travis-ci.org/rcreasey/OpenXcom)

**Comment by SupSuper** [comment]
What's this about: "This job ran on our legacy infrastructure. Please read our docs on how to upgrade"

**Comment by LavenderMoon** [comment]
If you don't use sudo at all, you can use the new Docker infrastructure for faster compiles and build caching. However, the new infrastructure doesn't support building for Mac.

**Comment by rcreasey** [comment]
Yeah, I'll have a follow up pull request for travis containers:
https://github.com/rcreasey/OpenXcom/tree/feature/travis-container

I'm waiting on them adding a couple more packages to be accepted to their whitelist:
https://github.com/travis-ci/apt-package-whitelist/issues/1000
https://github.com/travis-ci/apt-package-whitelist/issues/1001

And then container builds will be good to go:
https://travis-ci.org/rcreasey/OpenXcom/builds/77102116

As for osx builds on containers, they're only doing those as VMs right now (since you can't containerize a mac just yet).  As you can see from that above linked build, those will just fallback onto the osx infrastructure, while the linux builds are handled by docker infrastructure.

This pull request is good to go though. :+1:

**Comment by JonnyH** [comment]
I actually looked into this a bit earlier and there's already an outstanding apt-whitelist request for libsdl-mixer1.2-dev https://github.com/travis-ci/apt-package-whitelist/issues/715 - apparently they grep for 'suid' so it matches documents and everything....

**Comment by rcreasey** [comment]
Good catch @JonnyH.  I guess I fail at searching.

Let's move the container discussion to this pull request since this one has been merged: https://github.com/SupSuper/OpenXcom/pull/1048

**Pull request merged**
