### PR TITLE
Feature: unhardcoded first turn when AI can use grenades.

### PR DESCRIPTION
**Pull request by redv**
Topic: http://openxcom.org/forum/index.php/topic,3219.30.html

Unhardcoded first turn when AI can use grenades or Blaster launcher.

### CODE REVIEW

**Comment by Yankes** [comment]
And blast bombs... I think better would be if this was per weapon.

**Comment by redv** [comment]
I found another check for grenades in the getNodeOfBestEfficacy() but i can't find where a check of getTurn() for the launch of Blaster bomb.

**Comment by Yankes** [comment]
Ups.. I thought about `explosiveEfficacy` that have this test too. I mix both (when I last visit this code Warboy didn't add node version).

**Comment by redv** [comment]
Added option for first turn for Blaster launcher.
Thank you)

**Comment by redv** [comment]
Alternative version: https://github.com/SupSuper/OpenXcom/pull/996

**Pull request merged**
