### PR TITLE
Add includes for updated yaml-cpp used to be able to build in VS2015.

### PR DESCRIPTION
**Pull request by hartmark**
http://openxcom.org/forum/index.php/topic,3937.msg59985.html

### CODE REVIEW

**Comment by SupSuper** [comment]
Can you remove the 2015 solution file from the pull request?

**Comment by hartmark** [comment]
Sure, 

Should I create a new PR for the solution file. Or is that not interesting? 

On 3 March 2016 16:57:10 CET, Daniel <notifications@github.com> wrote:
>Can you remove the 2015 solution file from the pull request?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SupSuper/OpenXcom/pull/1086#issuecomment-191825715

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SupSuper** [comment]
I don't think there's any point as it's autoupgraded by whatever VS you use (I'm using VS2015 myself), so its best for the repository to have the lowest compatible version.

**Comment by hartmark** [comment]
I think I have managed to fix it now, I'm a bit noob with git/github so poke me if I have done anything wrong :)

We should have the prebuilt binaries also on the wiki so people in the future can build it with VS2015

**Comment by hartmark** [comment]
I didn't know that all changes done in my fork is automatically added to the pull request, I'll remember to have a branch next time so I don't clutter the pull requests.

Should I revert the last commit that merged the latest commit in upstream? Or does it not matter? I'm a bit noob with this git/github environment.

**Comment by SupSuper** [comment]
Yeah pull requests are tied to the branch, so you should never PR master. For the sake of keeping things uncluttered, I would suggest closing this and creating a new clean pull request.
For example you can create a new branch from "upstream/master" point, cherry pick the new commit(s) that add the includes into it, and then pull request that branch.

**Comment by hartmark** [comment]
I have created a new pull request now. Closing this one now. Thanks for your patiense with my noobness.

**Pull request closed without merging**
